export const images = {
    algorithmia: "images/EventImages/algorithmia.png",
    quantQuest: "images/EventImages/quantQuest.png",
    analytica: "images/EventImages/analytica.png",
    gpt: "images/EventImages/gpt.png",
    genethon: "images/EventImages/genethon.png",
    bugBountyBlitz: "images/EventImages/bugBountyBlitz.png",
    lastManStanding: "images/EventImages/lastManStanding.png",
    cosmicCraftathon: "images/EventImages/cosmicCraftathon.png",
    renderRiot: "images/EventImages/renderRiot.png",
    designathon: "images/EventImages/designathon.png",
    cypherChronicles: "images/EventImages/cypherChronicles.png",
    enigmaXplore: "images/EventImages/enigmaXplore.png",
    womenInDev: "images/EventImages/womenInDev.png",
    roboRumble: "images/EventImages/roboRumble.png",
    byteCraft: "images/EventImages/byteCraft.png",
    trailTracer: "images/EventImages/trailTracer.png",
    digitalTimeCapsule: "images/EventImages/digitalTimeCapsule.png",
    brandxperience: "images/EventImages/brandXperience.png",
    royalShowdown: "images/EventImages/royalShowdown.png",
    chessShatranjUp: "images/EventImages/chessShatranjUp.png",
    freeFire: "images/EventImages/freeFire.png",
    codm: "images/EventImages/codm.png",
    vyaparVichar: "images/EventImages/vyaparVichar.png",
    innovationOasis: "images/EventImages/innovationOasis.png",
    codefiesta: "images/EventImages/codefiesta.png",
    mysterySolver: "images/EventImages/mysterySolver.png"
  };
  